Vagrant.configure('2') do |config|
  config.vm.box      = 'ubuntu/trusty64'
  config.vm.hostname = 'rails-dev'

  config.vm.network :forwarded_port, guest: 3000, host: 3030

  config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true
end